
FROM python:3.9-slim

RUN mkdir flask
WORKDIR /flask


COPY requirements.txt  requirements.txt


RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY app.py .


EXPOSE 8001


CMD ["python", "app.py"]
